default_steps: &default_steps
  steps:
    #- <<: *install_build_tools
    - checkout
    - run:
        name: install dependencies
        command: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          sed -i "s/PROJECTVERSION/`python get_build_version.py`/g" setup.py
          pip install .

upload_to_pypi: &upload_to_pypi
  steps:
    #- <<: *install_build_tools
    - checkout
    - run:
        name: package and upload
        command: |
          python -m venv venv
          . venv/bin/activate
          pip install twine
          sed -i "s/PROJECTVERSION/`python get_build_version.py`/g" setup.py
          python setup.py sdist
          twine upload dist/*

jobs:
  python3.13:
    docker:
      - image: cimg/python:3.13.2
    working_directory: ~/repo
    <<: *default_steps
  deploy:
    docker:
      - image: cimg/python:3.13.2
    working_directory: ~/repo
    <<: *upload_to_pypi


workflows:
  build_and_test:
    stages:
      - python3.13
      #- deploy:
      #    run_when:
      #      branch: 'master'
      #      tag: '^\d+\.\d+\.\d+$'

      #    requires:
      #      - python3.6
