install_build_tools: &install_build_tools
  run:
      name: install build tools
      command: |
        apk add git build-base libffi-dev

default_steps: &default_steps
  steps:
    #- <<: *install_build_tools
    - checkout
    - run:
        name: install dependencies
        command: |
          python -m venv venv
          chmod -R a+rwx /usr/share
          . venv/bin/activate
          pip install .

upload_to_pypi: &upload_to_pypi
  steps:
    #- <<: *install_build_tools
    - checkout
    - run:
        name: init .pypirc
        command: |
          echo -e "[pypi]" >> ~/.pypirc
          echo -e "username = chestm007" >> ~/.pypirc
          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

    - run:
        name: package and upload
        command: |
          python -m venv venv
          . venv/bin/activate
          pip install twine
          sed -i "s/0.0.1/`python get_build_version.py`/g" setup.py
          python setup.py sdist
          twine upload dist/*

jobs:
  python3.13:
    docker:
      - image: cimg/python:3.13.2
    working_directory: ~/repo
    <<: *default_steps
  deploy:
    docker:
      - image: cimg/python:3.13.2
    working_directory: ~/repo
    <<: *upload_to_pypi


workflows:
  build_and_test:
    stages:
      - python3.13
      #- deploy:
      #    run_when:
      #      branch: 'master'
      #      tag: '^\d+\.\d+\.\d+$'

      #    requires:
      #      - python3.6
