default_steps: &default_steps
  steps:
    - run:
        name: install git
        command: |
          apk add git build-base
    - checkout
    - run:
        name: install dependencies
        command: |
          python -m venv venv
          chmod -R a+rwx /usr/share
          . venv/bin/activate
          pip install .

upload_to_pypi: &upload_to_pypi
  steps:
    - checkout
    - run:
        name: init .pypirc
        command: |
          echo -e "[pypi]" >> ~/.pypirc
          echo -e "username = chestm007" >> ~/.pypirc
          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

    - run:
        name: package and upload
        command: |
          sudo apt-get install -y virtualenv
          python -m venv venv
          . venv/bin/activate
          pip install twine
          sed -i "s/PROJECTVERSION/`python get_build_version.py`/g" setup.py
          python setup.py sdist
          twine upload dist/*

jobs:
  python3.6:
    docker:
      - image: python:3.6.15-alpine
    working_directory: ~/repo
    <<: *default_steps
  python3.7:
    docker:
      - image: python:3.7.12-alpine
    working_directory: ~/repo
    <<: *default_steps
  deploy:
    docker:
      - image: python:3.7.12-alpine
    working_directory: ~/repo
    <<: *upload_to_pypi


workflows:
  build_and_test:
    stages:
      - python3.6
      - python3.7
      - deploy:
          run_when:
            branch: 'master'
            tag: '^\d+\.\d+\.\d+$'

          requires:
            - python3.6
            - python3.7
