# place this file in '/etc/zeus-ci/' and edit to suit.

logging:
  level: INFO
#   filepath:
#   use_journal:
#   format:

database:
  protocol: sqlite
  args: /etc/zeus-ci/database.db

# listener:
#   listen_address:
#   port:

# build_coordinator:
#   runner_threads:
#   concurrent_builds:
#   build_poll_sec:

# resource_allocator:
#   address:
#   port: